# Generated by Django 5.2.6 on 2025-09-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_file_key_message_mime_type_message_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='presigned_file_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
