# Generated by Django 5.2.6 on 2025-10-04 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_user_thumbnail'),
        ('groupchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groupchat.chatgroup'),
        ),
    ]
